//
//  File.swift
//  
//
//  Created by Nikolai Baklanov on 17.04.2023.
//

import Foundation

let emailMarkerWords = [
    "www",
    ".COM",
    "https",
    "http",
    ".com",
    "@",
    "Email:",
    "email:",
    ".net",
    ".edu"
]

let townsAbbrevationsMarkerWords = [
    "new york",
    "los angeles",
    "chicago",
    "houston",
    "philadelphia",
    "phoenix",
    "san antonio",
    "san diego",
    "dallas",
    "san jose",
    "honolulu",
    "austin",
    "indianapolis",
    "jacksonville",
    "san francisco",
    "columbus",
    "charlotte",
    "fort worth",
    "detroit",
    "el passo"
]

let addressAbbrevationsMarkerWords = [
    " ca",
    " id",
    " ia",
    " al",
    " ak",
    " az",
    " ar",
    " wy",
    " wa",
    " dc",
    " vt",
    " va",
    " wi",
    " hi",
    " de",
    " ga",
    " wv",
    " il",
    " in",
    " ks",
    " ky",
    " co",
    " ct",
    " la",
    " ma",
    " mn",
    " ms",
    " mo",
    " mi",
    " mt",
    " me",
    " md",
    " ne",
    " nv",
    " nh",
    " nj",
    " ny",
    " nm",
    " oh",
    " ok",
    " or",
    " pa",
    " ri",
    " nd",
    " nc",
    " tn",
    " tx",
    " fl",
    " sd",
    " sc",
    " ut"
]

let addressPlacesMarkerWords = [
    "ave",
    "suite",
    "street",
    "bvld",
    "unit",
    "circle",
    "citu",
    "gate",
    "coast",
    "highway",
    "avenue",
    "road",
    "rd",
    "place",
    " usa",
    "hwy",
    "floor",
    "box",
]

let companyNameMarkerWords = [
    "co.",
    "tech",
    "group",
    "solutions",
    "associates",
    ", inc",
    ", inc.",
    ", Inc",
    "company",
    "technologies",
    "llc",
    "global",
    "tm",
    "corp.",
]

let professionsNameMarkerWords = [
    "Sales/Lightning Specialist",
    "Sales representative",
    "Sales",
    "Vice president",
    "Channel Sales Manager",
    "Manufacturers representative",
    "Sales/LV Specialist",
    "Purchasing coordinator",
    "Manager Special Projects/LED",
    "Lighting Quotations Specialist",
    "Store Manager",
    "Marketing Director/Partner",
    "Project Manager",
    "Director of Sales",
    "Account Manager",
    "FAE/Project Manager",
    "President",
    "Regional Sales Manager",
    "Territory Manager",
    "President",
    "Arbonne Independent Consultant",
    "Store Supervisor",
    "Sales director",
    "Operations manager",
    "Client service representative",
    "President",
    "Business development representative",
    "Sales manager",
    "Marketing supervisor",
    "Sales executive",
    "Marketing Communications manager",
    "Accounts manager",
    "CEO/Partner",
    "Senior horticulturist",
    "General manager",
    "Store manager",
    "Project manager",
    "President",
    "Western Regional Sales manager",
    "Vice president of C&I Sales",
    "Regional Sales manager",
    "Chairman",
    "Regional manager",
    "Regional Sales manager",
    "Product manager",
    "Product manager",
    "Marketing Specialist",
    "Marketing Manager",
    "Marketing Director",
    "Graphic Designer",
    "Marketing Research Analyst",
    "Marketing Communications Manager",
    "Marketing Consultant",
    "Product Manager",
    "Public Relations",
    "Social Media Assistant",
    "Brand Manager",
    "SEO Manager",
    "Content Marketing Manager",
    "Copywriter",
    "Media Buyer",
    "Digital Marketing Manager",
    "eCommerce Marketing Specialist",
    "Brand Strategist",
    "Vice President of Marketing",
    "Media Relations Coordinator",
    "Sales Associate",
    "Sales Representative",
    "Sales Manager",
    "Retail Worker",
    "Store Manager",
    "Sales Representative",
    "Sales Manager",
    "Real Estate Broker",
    "Sales Associate",
    "Cashier",
    "Store Manager",
    "Account Executive",
    "Account Manager",
    "Area Sales Manager",
    "Direct Salesperson",
    "Director of Inside Sales",
    "Outside Sales Manager",
    "Sales Analyst",
    "Market Development Manager",
    "B2B Sales Specialist",
    "Sales Engineer",
    "Merchandising Associate",
    "Team Leader",
    "Manager",
    "Assistant Manager",
    "Executive",
    "Director",
    "Coordinator",
    "Administrator",
    "Controller",
    "Officer",
    "Organizer",
    "Supervisor",
    "Superintendent",
    "Head",
    "Overseer",
    "Chief",
    "Foreman",
    "Controller",
    "Principal",
    "President",
    "Lead"
]

let utilsMarkerWords = [
   "service",
   "business",
   "sales",
   "office",
   "group",
   "advanced",
   "center",
   "city",
   "college",
   "specialist",
   "associates",
   "product",
   "senior",
   "manufacturer",
   "co.",
   "department",
   "division",
   "electric",
   "suply",
   "fund",
   "done",
   "light",
   "wholesale",
   "consultant",
   ".com",
   "www.",
   "save",
   "state",
   "states",
   "southern",
   "global",
]


